const pencilButton = document.getElementById('pencil')
const eraserButton = document.getElementById('eraser')
const squareButton = document.getElementById('quadrado')
const scissorsButton = document.getElementById('scissors')
const buttons = document.querySelectorAll('button')
